---
title: "Teste elo"
output: html_notebook
---

## Baseado em: https://edomt.github.io/Elo-R-WorldCup/

```{r, warning = FALSE, message = FALSE}
library(stringr)
library(dplyr)
library(RcppBDT) # https://stackoverflow.com/questions/23354069/how-to-figure-third-friday-of-a-month-in-r
library(elo)
```

```{r}
arruma_data <- function(x) {
  if(nchar(x) == 15) {
    ano1 = str_sub(x, start = 7, end = 10)
    ano2 = str_sub(x, start = 12, end = 15)
    if(as.integer(str_sub(x, start = 4, end = 5)) >= 7) {
      x = (paste0(str_sub(x, start = 1, end = 6), ano1))
    } else {
      x = (paste0(str_sub(x, start = 1, end = 6), ano2))
    }
  }
  as.Date(x, "%d.%m.%Y")
}
```

```{r}
files = list.files("data") 

partidas = files %>%
  lapply(function(x) read.csv(paste0("data/", x), stringsAsFactors = FALSE, encoding = "UTF-8") %>%
           mutate(file = str_sub(x, start = 1, end = -5))) %>%
  do.call(rbind, .) %>%
  rowwise() %>%
  mutate(date = arruma_data(date)) %>%
  filter(date >= "2002-01-01") %>%
  arrange(date) %>%
  mutate(result = if_else(goals_1 > goals_2, 1,
                          if_else(goals_1 == goals_2, 0.5, 0)))
```

```{r}
clubes_paises = tibble(Clube = c(partidas$club_1, partidas$club_2),
                       Pais = c(partidas$file, partidas$file)) %>%
  distinct(Clube, Pais) %>%
  filter(Pais != "Continentais")
```

```{r}
partidas = partidas %>%
  filter(file != "Continentais") # pra não dar problema lá embaixo, tem times que só estão nos continentais, Monarcas por exemplo
```

```{r}
tercas = getNthDayOfWeek(first, Tue, 1, 2002)
for(ano in 2002:2019) {
  for(mes in 1:12) {
    tercas = c(tercas, getNthDayOfWeek(first, Tue, mes, ano))
  }
}
tercas = tercas[-c(1, 215:217)]
tercas
```

```{r}
write.table(tercas, file = "tercas.csv", sep = ";", na = "", row.names = FALSE, col.names = FALSE)
```

```{r}
partidas_meses = list()
for(i in 1:(length(tercas)-1)) {
  partidas_meses[[i]] = partidas %>%
    filter(date >= tercas[i],
           date < tercas[i+1])
}
```

```{r}
clubes = data.frame(Clube = unique(c(partidas$club_1, partidas$club_2)), Elo = 1500) %>%
  inner_join(clubes_paises) %>%
  distinct(Clube, .keep_all = TRUE) %>% # EXISTEM CLUBES DE PAISES DIFERENTES, BOCA JUNIORS DA COLOMBIA POR EXEMPLO
  mutate(Clube = as.factor(Clube))
```

```{r}
clubes_meses = list()
```

```{r}
for(mes in 1:length(partidas_meses)) {
    
  for (i in seq_len(nrow(partidas_meses[[mes]]))) {
    
  partida = partidas_meses[[mes]][i,]
  
  clubA_elo = subset(clubes, Clube == partida$club_1)$Elo
  clubB_elo = subset(clubes, Clube == partida$club_2)$Elo
  
  new_elo = elo.calc(wins.A = partida$result,
                      elo.A = clubA_elo,
                      elo.B = clubB_elo,
                      k = 20)
  
  clubA_new_elo = new_elo[1, 1]
  clubB_new_elo = new_elo[1, 2]
  
  clubes = clubes %>%
    mutate(Elo = if_else(Clube == partida$club_1, clubA_new_elo,
                         if_else(Clube == partida$club_2, clubB_new_elo, Elo)))
  
  }
  clubes_meses[[mes]] = clubes
}
```

```{r}
for(i in 1:length(clubes_meses)) {
  clubes_meses[[i]]$Data = tercas[i+1]
}
```

```{r}
dados = do.call(rbind, clubes_meses) %>%
  mutate(Clube = as.character(Clube))

save(dados, file = "dados.RData")
```

